/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import entities.Hospital;
import entities.User;
import javax.swing.JOptionPane;
import models.DataStorageClass;

/**
 *
 * @author HarshilaJagtap
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public LoginScreen() {
        //Uncomment initcomments later
        initComponents();
//           dispose();
//           this.setVisible(false);
//           new SuperAdminDashboardScreen().setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login_Screen_Login_Button = new javax.swing.JButton();
        LoginScreen_username_textfield = new javax.swing.JTextField();
        LoginScreen_password_textfield = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_superadminButton = new javax.swing.JButton();
        Login_Screen_Register_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 576));

        Login_Screen_Login_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Login_Screen_Login_Button.setText("LOGIN");
        Login_Screen_Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Screen_Login_ButtonActionPerformed(evt);
            }
        });

        LoginScreen_username_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoginScreen_username_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginScreen_username_textfieldActionPerformed(evt);
            }
        });

        LoginScreen_password_textfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Password");

        login_superadminButton.setText("SUPER ADMIN");
        login_superadminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_superadminButtonActionPerformed(evt);
            }
        });

        Login_Screen_Register_Button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Login_Screen_Register_Button.setText("REGISTER");
        Login_Screen_Register_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_Screen_Register_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(login_superadminButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Login_Screen_Register_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Login_Screen_Login_Button))
                    .addComponent(LoginScreen_password_textfield)
                    .addComponent(LoginScreen_username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginScreen_username_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LoginScreen_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_Screen_Register_Button)
                    .addComponent(Login_Screen_Login_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_superadminButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginScreen_username_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginScreen_username_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginScreen_username_textfieldActionPerformed

    private void Login_Screen_Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Screen_Login_ButtonActionPerformed
        // TODO add your handling code here:
        String username = LoginScreen_username_textfield.getText().trim();
        String password = new String(LoginScreen_password_textfield.getPassword());
        System.out.println("username " + username + " password " + password);
        if (username.equals("superadmin") && password.equals("bestproject")) {
            DataStorageClass.USERROLE = "SUPER_ADMIN";
            dispose();
            new SuperAdminDashboardScreen().setVisible(true);
        }else        if (!DataStorageClass.userArrayList.isEmpty()) {
            for (int i = 0; i < DataStorageClass.userArrayList.size(); i++) {
               System.out.println("username stored " + DataStorageClass.userArrayList.get(i).getId() + " password stored " + DataStorageClass.userArrayList.get(i).getPassword()
               + " role " + DataStorageClass.userArrayList.get(i).getRole() + " size " + DataStorageClass.userArrayList.size());
                if (DataStorageClass.userArrayList.get(i).getId().equals(username) && DataStorageClass.userArrayList.get(i).getPassword().equals(password)) {
                    User user = new User();
                    user = DataStorageClass.userArrayList.get(i);
                    switch (user.getRole()) {

                        case "HOSPITAL" -> {
                            DataStorageClass.USERROLE = "HOSPITAL";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        }
                        
                        case "DOCTOR" -> {
                            DataStorageClass.USERROLE = "DOCTOR";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        } 
                        case "PATIENT" -> {
                            DataStorageClass.USERROLE = "PATIENT";
                            DataStorageClass.USERID = user.getId();
                            dispose();
                            new SuperAdminDashboardScreen().setVisible(true);
                        }
                    }
i = DataStorageClass.userArrayList.size();
                }
                
            }

        } else {
            JOptionPane.showMessageDialog(null, "No Users Found. Register First");
        }

    }//GEN-LAST:event_Login_Screen_Login_ButtonActionPerformed

    private void login_superadminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_superadminButtonActionPerformed
        // TODO add your handling code here:
           DataStorageClass.USERROLE = "SUPER_ADMIN";
            dispose();
            new SuperAdminDashboardScreen().setVisible(true);

    }//GEN-LAST:event_login_superadminButtonActionPerformed

    private void Login_Screen_Register_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_Screen_Register_ButtonActionPerformed
        // TODO add your handling code here:
        DataStorageClass.USERROLE = "PERSON";
        dispose();
        new SuperAdminDashboardScreen().setVisible(true);
    }//GEN-LAST:event_Login_Screen_Register_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField LoginScreen_password_textfield;
    private javax.swing.JTextField LoginScreen_username_textfield;
    private javax.swing.JButton Login_Screen_Login_Button;
    private javax.swing.JButton Login_Screen_Register_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_superadminButton;
    // End of variables declaration//GEN-END:variables
}
